2022-05-12 18:09:46
===============================
[master c358cf9] New backup 2022-05-12 18:09:46
 2 files changed, 4 insertions(+), 15 deletions(-)
To https://github.com/NotYasho/dotfiles.git
   c362ae9..c358cf9  master -> master

ERROR
===============================

2022-05-12 18:12:07
===============================
[master 257fe67] New backup 2022-05-12 18:12:07
 2 files changed, 10 insertions(+), 1 deletion(-)
To https://github.com/NotYasho/dotfiles.git
   c358cf9..257fe67  master -> master

SUCCESS
===============================

2022-05-12 18:16:09
===============================
[master 41784bf] New backup 2022-05-12 18:16:09
 6 files changed, 26 insertions(+), 32 deletions(-)
 rename log.log => .log (54%)
 delete mode 100644 log.txt
To https://github.com/NotYasho/dotfiles.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/NotYasho/dotfiles.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

ERROR
===============================

2022-05-12 18:17:43
===============================
